_extends: ysoftwareab/yplatform:repo/dot.github/settings.base.yml

repository:
  name: homebrew-tap
  description: Homebrew packages for https://github.com/ysoftwareab/yplatform

collaborators:
  - username: RobindeGrootNL
    permission: push
